version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: *****
      POSTGRES_USER: *****
      POSTGRES_PASSWORD: *****
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: "*****://****:*****@****:5432/*****"
    command: ["pytest", "test.py"]
