pipeline {
    agent {
        docker { image 'python:3.8' }
    }

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest'
            }
        }
        stage('Publish Results') {
            steps {
                junit 'reports/*.xml'
            }
        }
    }

    post {
        always {
            emailext (
                to: 'InsertYour@Mail.Here',
                subject: 'Build ${currentBuild.fullDisplayName}',
                body: 'Build ${currentBuild.fullDisplayName} (${env.BUILD_URL})',
                attachLog: true
            )
        }
    }
}
