pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'homework31/lesson_31', url: 'https://github.com/Hronologiya/AQA.git'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest'
            }
        }

        stage('Publish Results') {
            steps {
                junit '**/test-results/*.xml'
            }
        }
    }

    post {
        always {
            mail to: 'InsertYour@Mail.Here',
                 subject: "Build ${currentBuild.fullDisplayName}",
                 body: "Check console output at ${env.BUILD_URL} to view the results."
        }
    }
}
